name: Run Cron Job

on:
  schedule:
    - cron: "*/1 * * * *"
  workflow_dispatch:

jobs:
  trigger-cron:
    runs-on: ubuntu-latest
    steps:
      - name: Call Vercel Cron Endpoint
        run: |
          echo "Calling Vercel endpoint..."
          curl -X POST "https://scheduleyourjob.vercel.app/run-scheduled-jobs/" -w "\nHTTP STATUS: %{http_code}\n"
