name: Run Cron Job

on:
  schedule:
    - cron: "*/1 * * * *"  # Runs every 1 minute

jobs:
  trigger-cron:
    runs-on: ubuntu-latest
    steps:
      - name: Call Django Cron Endpoint
        run: |
          curl -X POST "https://scheduleyourjob.vercel.app/run-scheduled-jobs/"
