# Generated by Django 5.1.6 on 2025-02-24 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ScheduledJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
                ('method', models.CharField(choices=[('GET', 'GET'), ('POST', 'POST')], default='GET', max_length=4)),
                ('cron_expression', models.CharField(default='* * * * *', help_text='Cron format expression', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_executed_at', models.DateTimeField(blank=True, null=True)),
                ('interval_minutes', models.IntegerField(default=5)),
                ('next_run_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
